export const handleApiCallError = async (error, rejectWithValue) => {
  return rejectWithValue(error);
};
